### ISSUE TITLE
报错三天咯，求大佬修复😘

### ISSUE THREAD

**Issue by JUSWEN** [LihaoLikeOrangeJuice/clockIn_gzhu#5]

**Comment by LihaoLikeOrangeJuice** [comment]
你把你的项目更新一下应该就可以了

**Comment by cryonic** [comment]
貌似还是用不了？就一直卡在那
6m 42s
Run python clockIn_gzhu.py
[WDM] - ====== WebDriver manager ======

[WDM] - Current google-chrome version is [1](https://github.com/cryonic/clockIn_gzhu/runs/6643124724?check_suite_focus=true#step:5:1)01.0.4[9](https://github.com/cryonic/clockIn_gzhu/runs/6643124724?check_suite_focus=true#step:5:10)51
[WDM] - Get LATEST chromedriver version for [10](https://github.com/cryonic/clockIn_gzhu/runs/6643124724?check_suite_focus=true#step:5:11)1.0.4951 google-chrome
[WDM] - There is no [linux64] chromedriver for browser 101.0.4951 in cache
[WDM] - About to download new driver from https://chromedriver.storage.googleapis.com/101.0.4951.41/chromedriver_linux64.zip
[WDM] - Driver has been saved in cache [/home/runner/.wdm/drivers/chromedriver/linux64/101.0.4951.41]
2022-05-29 [11](https://github.com/cryonic/clockIn_gzhu/runs/6643124724?check_suite_focus=true#step:5:12):57:36.355 | INFO     | __main__:wd_login:52 - 第1次运行
2022-05-29 11:57:36.356 | INFO     | __main__:wd_login:81 - 正在转到统一身份认证页面
2022-05-29 11:58:06.107 | INFO     | __main__:wd_login:94 - 正在尝试登陆融合门户
2022-05-29 11:58:38.956 | INFO     | __main__:wd_login:110 - 正在转到学生健康状况申报页面
2022-05-29 [12](https://github.com/cryonic/clockIn_gzhu/runs/6643124724?check_suite_focus=true#step:5:13):02:22.175 | ERROR    | __main__:wd_login:172 - Traceback (most recent call last):
  File "/home/runner/work/clockIn_gzhu/clockIn_gzhu/clockIn_gzhu.py", line 115, in wd_login
    wdwait.until(
  File "/opt/hostedtoolcache/Python/3.9.12/x64/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 87, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55ee317f9533 <unknown>
#1 0x55ee315581e8 <unknown>
#2 0x55ee3158e2d7 <unknown>
#3 0x55ee3158e4a1 <unknown>
#4 0x55ee315c1494 <unknown>
#5 0x55ee315abf6d <unknown>
#6 0x55ee315bf224 <unknown>
#7 0x55ee315abe33 <unknown>
#8 0x55ee3158171a <unknown>
#9 0x55ee31582875 <unknown>
#10 0x55ee3183de1d <unknown>
#11 0x55ee31841751 <unknown>
#12 0x55ee3182807e <unknown>
#[13](https://github.com/cryonic/clockIn_gzhu/runs/6643124724?check_suite_focus=true#step:5:14) 0x55ee31842388 <unknown>
#[14](https://github.com/cryonic/clockIn_gzhu/runs/6643124724?check_suite_focus=true#step:5:15) 0x55ee3181cfe0 <unknown>
#[15](https://github.com/cryonic/clockIn_gzhu/runs/6643124724?check_suite_focus=true#step:5:16) 0x55ee3185e748 <unknown>
#[16](https://github.com/cryonic/clockIn_gzhu/runs/6643124724?check_suite_focus=true#step:5:17) 0x55ee3185e8c8 <unknown>
#[17](https://github.com/cryonic/clockIn_gzhu/runs/6643124724?check_suite_focus=true#step:5:18) 0x55ee3[18](https://github.com/cryonic/clockIn_gzhu/runs/6643124724?check_suite_focus=true#step:5:19)7870d <unknown>
#18 0x7ffa03c10609 <unknown>


[20](https://github.com/cryonic/clockIn_gzhu/runs/6643124724?check_suite_focus=true#step:5:21)[22](https://github.com/cryonic/clockIn_gzhu/runs/6643124724?check_suite_focus=true#step:5:23)-05-[29](https://github.com/cryonic/clockIn_gzhu/runs/6643124724?check_suite_focus=true#step:5:30) 12:02:22.175 | ERROR    | __main__:wd_login:173 - 第1次运行失败
2022-05-29 12:02:22.175 | INFO     | __main__:wd_login:52 - 第2次运行
2022-05-29 12:02:22.175 | INFO     | __main__:wd_login:57 - 刷新页面

**Comment by LihaoLikeOrangeJuice** [comment]
这个就是全部的日志吗？如果是的话，应该是程序还没有运行完你就取消了

**Comment by LihaoLikeOrangeJuice** [comment]
@cryonic 这个就是全部的日志吗？如果是的话，应该是程序还没有运行完你就取消了

**Comment by cryonic** [comment]
是取消了，因为感觉运行了很久。是网络的问题吗。

**Comment by LihaoLikeOrangeJuice** [comment]
确实是网络的问题

**Comment by LihaoLikeOrangeJuice** [comment]
@cryonic 确实是网络的问题，这个不好解决

**Comment by JUSWEN** [comment]
谢谢你！

on my iPhone
